version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: oidc_postgres
    restart: always
    environment:
      POSTGRES_USER: oidc_user
      POSTGRES_PASSWORD: oidc_pass
      POSTGRES_DB: oidc_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: oidc_redis
    ports:
      - "6383:6379"
    restart: always    

volumes:
  postgres_data: